### ISSUE TITLE
The vanilla client cannot enter a server that already has this mod installed

### ISSUE THREAD

**Issue by QianYI-Yan** [ColdLavaLamp/BigBeacons#3]
![image](https://github.com/user-attachments/assets/4f67b447-b2e3-4446-bf22-72b054ebe877)

**Comment by QianYI-Yan** [comment]
server 1.21
mod 1.2.7

**Comment by NateOnLinux** [comment]
I am running a 1.21 server with the same mod version and my vanilla players don't have this problem. We usually see this problem when running Fabric without BigBeacons installed. Maybe double check that it isn't a fabric client?

**Comment by QianYI-Yan** [comment]
> I am running a 1.21 server with the same mod version and my vanilla players don't have this problem. We usually see this problem when running Fabric without BigBeacons installed. Maybe double check that it isn't a fabric client?

How do I make the server not detect if the mod is installed?
